/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalcu extends javax.swing.JFrame {

    /**
     * Creates new form jfrmCalcu
     */
    private String entrada="";
    private int numero1, numero2;
    private String operador;
    public jfrmCalcu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtCantidad = new javax.swing.JTextField();
        jbtl7 = new javax.swing.JButton();
        jbtl8 = new javax.swing.JButton();
        jbtl9 = new javax.swing.JButton();
        jbtl1 = new javax.swing.JButton();
        jbtl2 = new javax.swing.JButton();
        jbtl3 = new javax.swing.JButton();
        jbtl4 = new javax.swing.JButton();
        jbtl5 = new javax.swing.JButton();
        jbtl6 = new javax.swing.JButton();
        jbtl0 = new javax.swing.JButton();
        jbtlborra = new javax.swing.JButton();
        jbtlrest = new javax.swing.JButton();
        jbtlmulti = new javax.swing.JButton();
        jbtldivi = new javax.swing.JButton();
        jbtlIgual = new javax.swing.JButton();
        jbtlsum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setEditable(false);
        jtxtCantidad.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jtxtCantidad.setText("0.0");
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });

        jbtl7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl7.setText("7");
        jbtl7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl7ActionPerformed(evt);
            }
        });

        jbtl8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl8.setText("8");
        jbtl8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl8ActionPerformed(evt);
            }
        });

        jbtl9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl9.setText("9");
        jbtl9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl9ActionPerformed(evt);
            }
        });

        jbtl1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl1.setText("1");
        jbtl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl1ActionPerformed(evt);
            }
        });

        jbtl2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl2.setText("2");
        jbtl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl2ActionPerformed(evt);
            }
        });

        jbtl3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl3.setText("3");
        jbtl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl3ActionPerformed(evt);
            }
        });

        jbtl4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl4.setText("4");
        jbtl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl4ActionPerformed(evt);
            }
        });

        jbtl5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl5.setText("5");
        jbtl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl5ActionPerformed(evt);
            }
        });

        jbtl6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl6.setText("6");
        jbtl6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl6ActionPerformed(evt);
            }
        });

        jbtl0.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtl0.setText("0");
        jbtl0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtl0ActionPerformed(evt);
            }
        });

        jbtlborra.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jbtlborra.setText("AC");
        jbtlborra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlborraActionPerformed(evt);
            }
        });

        jbtlrest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtlrest.setText("-");
        jbtlrest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlrestActionPerformed(evt);
            }
        });

        jbtlmulti.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtlmulti.setText("*");
        jbtlmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlmultiActionPerformed(evt);
            }
        });

        jbtldivi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtldivi.setText("/");
        jbtldivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtldiviActionPerformed(evt);
            }
        });

        jbtlIgual.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtlIgual.setText("=");
        jbtlIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlIgualActionPerformed(evt);
            }
        });

        jbtlsum.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jbtlsum.setText("+");
        jbtlsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlsumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtlmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtl0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtlIgual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtlsum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtldivi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtxtCantidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtl7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtl8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtl9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtl5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtl6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtlrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtlborra, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtl7)
                    .addComponent(jbtl8)
                    .addComponent(jbtl9)
                    .addComponent(jbtlborra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtl4)
                    .addComponent(jbtl5)
                    .addComponent(jbtl6)
                    .addComponent(jbtlrest))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtl1)
                    .addComponent(jbtl2)
                    .addComponent(jbtl3)
                    .addComponent(jbtlmulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtl0)
                    .addComponent(jbtlIgual)
                    .addComponent(jbtlsum)
                    .addComponent(jbtldivi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtl7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl7ActionPerformed
        // TODO add your handling code here:
        
        entrada= entrada+7;
        
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl7ActionPerformed

    private void jbtl8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl8ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl8ActionPerformed

    private void jbtl9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl9ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl9ActionPerformed

    private void jbtl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl1ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl1ActionPerformed

    private void jbtl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl2ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl2ActionPerformed

    private void jbtl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl3ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl3ActionPerformed

    private void jbtl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl4ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl4ActionPerformed

    private void jbtl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl5ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl5ActionPerformed

    private void jbtl6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl6ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl6ActionPerformed

    private void jbtl0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtl0ActionPerformed
        // TODO add your handling code here:
        entrada= entrada+0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtl0ActionPerformed

    private void jbtlIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlIgualActionPerformed
        // TODO add your handling code here:
        double resultado;
        numero2=Integer.parseInt(entrada);
        jtxtCantidad.setText("");
        if(operador.equals("*")){
            resultado=numero1*numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        
        }
        if(operador.equals("/")){
            resultado=numero1/numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        
        }
        if(operador.equals("+")){
            resultado=numero1+numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        
        }
        if(operador.equals("-")){
            resultado=numero1-numero2;
            entrada=String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        
        
        }
    }//GEN-LAST:event_jbtlIgualActionPerformed

    private void jbtlsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlsumActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="+";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtlsumActionPerformed

    private void jbtlrestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlrestActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="-";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtlrestActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void jbtlmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlmultiActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="*";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtlmultiActionPerformed

    private void jbtldiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtldiviActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="/";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtldiviActionPerformed

    private void jbtlborraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlborraActionPerformed
        // TODO add your handling code here:
        entrada="";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtlborraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtl0;
    private javax.swing.JButton jbtl1;
    private javax.swing.JButton jbtl2;
    private javax.swing.JButton jbtl3;
    private javax.swing.JButton jbtl4;
    private javax.swing.JButton jbtl5;
    private javax.swing.JButton jbtl6;
    private javax.swing.JButton jbtl7;
    private javax.swing.JButton jbtl8;
    private javax.swing.JButton jbtl9;
    private javax.swing.JButton jbtlIgual;
    private javax.swing.JButton jbtlborra;
    private javax.swing.JButton jbtldivi;
    private javax.swing.JButton jbtlmulti;
    private javax.swing.JButton jbtlrest;
    private javax.swing.JButton jbtlsum;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
